#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     ultrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main() {
	wait1Msec(1000);
	for(int i = 0;i < 4;i++) {
		motor[leftMotor] = 30;
		motor[rightMotor] = 30;
		wait1Msec(2300);

		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(100);

		moveMotorTarget(rightMotor, 390, 30);
		moveMotorTarget(leftMotor, 0, 30);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
	}
}
